export const SELECT_ROOM = "SELECT_ROOM";
export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";
export const REFRESH_ALL = "REFRESH_ALL";
export const LOAD_USER_HISTORY = "LOAD_USER_HISTORY";