export const SELECT_ROOM = "SELECT_ROOM";
export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const USER_FORM_SUBMIT = "USER_FORM_SUBMIT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SUCCESS = "AUTH_SUCCESS";